#!/usr/bin/env python3
"""Regenerate the "Models tested on AINode" table in README.md from bench/results/*.json.

Those numbers appear in prose in two repos (this README and the tested-models guide on
docs.ainode.dev), so the table is generated rather than typed. Add a result file, run
this, commit both:

    python3 scripts/render-bench-table.py            # rewrite README.md in place
    python3 scripts/render-bench-table.py --print    # emit the table, touch nothing
    python3 scripts/render-bench-table.py --check    # exit 1 if README.md is stale

Any file carrying the two markers can be the target, which is how the same table
lands in the tested-models guide on docs.ainode.dev (MDX needs JSX comments, not
HTML ones):

    python3 scripts/render-bench-table.py \
        --readme ../ainode-docs/guides/tested-models.mdx \
        --begin '{/* BEGIN bench-table */}' --end '{/* END bench-table */}'

Nothing is computed or extrapolated. A measurement that is missing from the JSON
renders as "not measured" and a run with no rubric renders as "not run"; neither
ever becomes a zero or a guess. See bench/SCHEMA.md for the record format.

# ponytail: stdlib only, so it runs in CI and in the slim image with nothing installed.
"""
import argparse
import json
import pathlib
import sys

BEGIN = "<!-- BEGIN bench-table (generated by scripts/render-bench-table.py) -->"
END = "<!-- END bench-table -->"
BASE_URL = "https://github.com/getainode/ainode/blob/main/bench/results"
NOT_MEASURED = "not measured"

HEADERS = [
    "Model",
    "Params / active",
    "Quant",
    "Placement",
    "Single-stream tok/s",
    "16 streams tok/s",
    "Rubric",
    "Date",
    "Run",
]


def load_runs(results_dir):
    """Every result JSON, newest run first."""
    runs = []
    for path in sorted(results_dir.glob("*.json")):
        with path.open() as fh:
            run = json.load(fh)
        run["_file"] = path.name
        runs.append(run)
    runs.sort(key=lambda r: r.get("stamp", ""), reverse=True)
    return runs


def fmt_params(model):
    params = model.get("params_b")
    active = model.get("active_b")
    if params is None:
        return NOT_MEASURED
    if model.get("arch") == "dense" or active is None or active == params:
        return f"{params:g}B dense"
    return f"{params:g}B / {active:g}B active"


def fmt_placement(placement):
    bits = []
    node = placement.get("node")
    if node:
        bits.append(node)
    gpus = placement.get("gpus")
    gpu = placement.get("gpu", "GPU")
    if gpus:
        bits.append(f"{gpus}× {gpu.replace('NVIDIA ', '')}")
    tp = placement.get("tp")
    if tp:
        bits.append(f"TP={tp}")
    line = ", ".join(bits) if bits else NOT_MEASURED
    if placement.get("stacked_with"):
        # Stacked runs share the node's memory with another engine, which caps
        # gpu_memory_utilization and therefore the KV cache. Say so in the row.
        line += " (stacked)"
    return line


def fmt_tok_s(value):
    return NOT_MEASURED if value is None else f"{value:.1f}"


def fmt_single_stream(results):
    return fmt_tok_s((results.get("single_stream") or {}).get("decode_tok_s"))


def fmt_aggregate(results, streams=16):
    for point in results.get("concurrency") or []:
        if point.get("streams") == streams:
            return fmt_tok_s(point.get("aggregate_tok_s"))
    return NOT_MEASURED


def fmt_rubric(run):
    rubric = run.get("rubric") or {}
    passed, total = rubric.get("pass"), rubric.get("total")
    if passed is None or total is None:
        return "not run"
    return f"{passed}/{total}"


def fmt_date(stamp):
    if not stamp or len(stamp) < 8:
        return "unknown"
    return f"{stamp[0:4]}-{stamp[4:6]}-{stamp[6:8]}"


def row_for(run, base_url):
    model = run.get("model") or {}
    label = run.get("label") or "run"
    return [
        model.get("name") or model.get("id") or "unknown",
        fmt_params(model),
        model.get("quant") or NOT_MEASURED,
        fmt_placement(run.get("placement") or {}),
        fmt_single_stream(run.get("results") or {}),
        fmt_aggregate(run.get("results") or {}),
        fmt_rubric(run),
        fmt_date(run.get("stamp")),
        f"[{label}]({base_url}/{run['_file']})",
    ]


def render_table(runs, base_url=BASE_URL):
    # Unpadded cells and a `|---|` rule, matching the other tables in README.md.
    lines = [
        "| " + " | ".join(HEADERS) + " |",
        "|" + "---|" * len(HEADERS),
    ]
    for run in runs:
        lines.append("| " + " | ".join(row_for(run, base_url)) + " |")
    return "\n".join(lines)


def splice(text, table, begin=BEGIN, end=END):
    """Replace whatever sits between the markers. Both markers must already exist."""
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1:
        raise SystemExit(f"markers not found in target file; expected\n  {begin}\n  {end}")
    if stop < start:
        raise SystemExit("end marker appears before begin marker")
    head = text[: start + len(begin)]
    tail = text[stop:]
    return f"{head}\n\n{table}\n\n{tail}"


def main():
    repo = pathlib.Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--results", type=pathlib.Path, default=repo / "bench" / "results")
    ap.add_argument("--readme", type=pathlib.Path, default=repo / "README.md",
                    help="file to rewrite; any file carrying the two markers works, which "
                         "is how the docs-site guide gets the same table")
    ap.add_argument("--begin", default=BEGIN, help="opening marker (MDX needs {/* ... */})")
    ap.add_argument("--end", default=END, help="closing marker")
    ap.add_argument("--base-url", default=BASE_URL, help="where the JSON files are browsable")
    ap.add_argument("--print", dest="print_only", action="store_true",
                    help="write the table to stdout and leave README.md alone")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if README.md does not already match the JSON")
    args = ap.parse_args()

    runs = load_runs(args.results)
    if not runs:
        raise SystemExit(f"no result files in {args.results}")
    table = render_table(runs, args.base_url)

    if args.print_only:
        print(table)
        return 0

    current = args.readme.read_text()
    updated = splice(current, table, args.begin, args.end)
    if args.check:
        if current != updated:
            print(f"{args.readme} is stale; run python3 scripts/render-bench-table.py",
                  file=sys.stderr)
            return 1
        print(f"{args.readme} is up to date ({len(runs)} runs)")
        return 0
    if current == updated:
        print(f"{args.readme} already up to date ({len(runs)} runs)")
        return 0
    args.readme.write_text(updated)
    print(f"{args.readme} updated ({len(runs)} runs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
